### PR TITLE
Small Update

### PR DESCRIPTION
**Pull request by Felli**

### CODE REVIEW

**Comment by Eole211** [comment]
Hello !
Thank you for contributing.
Does this small update has anything to do with redlaguna's problem ? https://github.com/Eole211/HumShare/issues/2
Or maybe it's just a coincidence..
Also, is ActiveForm an updated version of CActiveForm ?
Thanks

**Comment by Felli** [comment]
This update is for the future v1.3 as all CActiveForm will be removed and be replaced, and `yii\helpers\Html` is better used over using `yii\bootstrap\Html` in some cases.

**Comment by Eole211** [comment]
You forgot some "s", at the end of yii/widgets and yii/helpers ... I fixed it

**Comment by Eole211** [comment]
And in fact ActiveForm and CActiveForm don't work the same way ,.. 
I'm going to change it back to CActiveForm for now

**Pull request merged**
